---
title: "Ejercicio 10. Radio del átomo de Wolframio"
author: "Aurelio Gallardo Rodríguez"
date: "3 de septiembre de 2017"
output:
  slidy_presentation:
    fig.align: center
    fig_caption: yes
    fig_height: 6
    fig_width: 10
    footer: Por Aurelio Gallardo
    highlight: pygments
  ioslides_presentation: default
subtitle: Pag 63. Everest. Ej. 9.  TINII.
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
```

## Ejercicio 10. $R_{Wolframio}$.
<p style="text-align:justify;">
La densidad del wolframio es de 19.3 g/cm3 y su masa atómica 183.9 g/mol. Sabiendo que empaqueta en una red BCC, calcula el radio de los átomos de Wolframio.
</p>
<hr>

```{r datos0, echo=FALSE, warning=FALSE}
library("units")
nat=2 ## número de átomos
mat=set_units(183.9,g/mol) ## masa atómica
d=set_units(19.3,g/cm^3)
NumA=set_units(6.022e23,1/mol) ## Número de avogadro
## Radio
intermedio = (nat*mat/NumA)/d
R= (intermedio)^(1/3)*sqrt(3)/4
R2=R
units(R2)=with(ud_units,Å)
```

<p style="text-align:justify;">
Para la red BCC, el número de átomos es __2__ y el volumen de la celda $V_{celda}=\left ( \frac{4 \cdot R}{\sqrt{3}} \right )^3$ 
</p>
<p style="text-align:justify;">
La expresión de la densidad $$\rho = \frac{m_{celda}}{V_{celda}}=\frac{n_{at} \cdot m_{at} / N_{A}}{\left ( \frac{4 \cdot R}{\sqrt{3}} \right )^3}$$
</p>

## Solución
<p style="text-align:justify;">
Despejamos R.
$$ R=\frac{\sqrt{3}}{4} \cdot \sqrt[3]{\frac{n_{at} \cdot m_{at} / N_{A}}{\rho}} = \\ =\frac{\sqrt{3}}{4} \cdot \sqrt[3]{\frac{`r nat` \,at \cdot `r mat`\,g/mol \cdot  \frac{1\,mol}{`r NumA`\,at} }{`r d` \cdot g/cm^3}} = \\ =\frac{\sqrt{3}}{4} \cdot \sqrt[3]{`r intermedio`\;cm^3} = \\ = `r formatC(R,digits=6,format="G") `\; cm = `r formatC(R2,digits=4,format="fg") `\; Å $$
</p>



